spring:
  application:
    name: Ragnarok
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    fail-on-missing-locations: true

logging:
  level:
    org:
      flywaydb: DEBUG

api:
  security:
    token:
      secret: minha-chave-secreta-super-poderosa-ragnarok-123