spring:
  application:
    name: Oryn
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    fail-on-missing-locations: true

logging:
  level:
    org:
      flywaydb: DEBUG

springdoc:
  swagger-ui:
    path: /docs

r2:
  endpoint: ${R2_ENDPOINT}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}

api:
  security:
    token:
      secret: ${JWT_SECRET}